---
repo_path: /home/bootcamp/problems
navigator_url: "https://navigator.bootcamp.wethinkco.de"
username: ""
review_manager_url: "https://review-manager.bootcamp.wethinkco.de"
keycloak_url: "https://keycloak.bootcamp.wethinkco.de"
